### ISSUE TITLE
Asynchronous/parallel running of accounts

### ISSUE THREAD

**Issue by tboy1337** [masterking32/MasterCryptoFarmBot#36]
One by one approach is ok with a small number of accounts but the more accounts you have the worse it is. With 50+ accounts it takes many hours to get back to the first account. I really can't stress enough how important this feature is.

**Comment by masterking32** [comment]
> One by one approach is ok with a small number of accounts but the more accounts you have the worse it is. With 50+ accounts it takes many hours to get back to the first account. I really can't stress enough how important this feature is.

Handling account processing depends on the specific modules being used. If you encounter issues related to a particular module, please create an issue for that module, not here. By the way, in my own modules, I avoid processing accounts due to rate limits. However, if you have any issues or suggestions regarding this, they are not related to the main MCF. Make sure to create an issue for the specific module you’re having trouble with.

**Comment by tboy1337** [comment]
Sorry I thought it would be the framework which would determine that.
